import { useState } from "react";
import { Link } from "wouter";
import { AlertTriangle, CheckCircle2, Clock3, ExternalLink, Loader2, ShieldCheck, SlidersHorizontal } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";

const REVIEW_LABELS: Record<string, string> = { low_confidence: "낮은 신뢰도", fallback_used: "폴백 발생", provider_failed: "모델 처리 실패", invalid_model_contract: "응답 규격 오류", score_disagreement: "규칙·모델 점수 차이", source_verification_failed: "출처 검증 실패", excessive_sentence_change: "과도한 문장 수정" };

export default function AdminEvaluationModels() {
  const utils = trpc.useUtils();
  const [modelId, setModelId] = useState("");
  const [endpoint, setEndpoint] = useState("");
  const [allowedDomains, setAllowedDomains] = useState("");
  const [apiKey, setApiKey] = useState("");
  const [timeoutMs, setTimeoutMs] = useState("15000");
  const configs = trpc.evaluationModels.list.useQuery();
  const operationStats = trpc.evaluationModels.operationStats.useQuery();
  const reviewQueue = trpc.evaluationModels.reviewQueue.useQuery();
  const appeals = trpc.evaluationAppeals.list.useQuery();
  const saveModel = trpc.evaluationModels.save.useMutation({ onSuccess: () => { setApiKey(""); utils.evaluationModels.list.invalidate(); toast.success("외부 첨삭 모델 설정을 암호화하여 저장했습니다."); }, onError: (error) => toast.error(error.message || "모델 설정을 저장하지 못했습니다.") });
  const updateReview = trpc.evaluationModels.updateReviewQueue.useMutation({ onSuccess: () => utils.evaluationModels.reviewQueue.invalidate() });
  const updateAppeal = trpc.evaluationAppeals.update.useMutation({ onSuccess: () => utils.evaluationAppeals.list.invalidate() });
  const save = () => {
    const domains = allowedDomains.split(",").map((domain) => domain.trim()).filter(Boolean);
    if (!modelId || !endpoint || !apiKey || domains.length === 0) return toast.error("모델 ID, HTTPS Endpoint, 허용 도메인, API 키를 모두 입력하세요.");
    saveModel.mutate({ modelId, endpoint, allowedDomains: domains, apiKey, timeoutMs: Number(timeoutMs), isActive: true });
  };
  return <div className="min-h-screen bg-slate-50 py-6 sm:py-8"><div className="mx-auto max-w-6xl space-y-6 px-4 sm:px-6 lg:px-8"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-bold text-indigo-700">관리자 운영</p><h1 className="mt-1 text-3xl font-extrabold text-slate-950">AI 첨삭 모델 운영</h1><p className="mt-2 text-sm leading-6 text-slate-600">외부 첨삭 Endpoint, 실행 품질, 인간 검수와 이의제기를 한곳에서 관리합니다.</p></div><Link href="/admin"><Button variant="outline">관리자 대시보드로 돌아가기</Button></Link></div>
    <Card className="border-indigo-200"><CardHeader><CardTitle className="flex items-center gap-2"><SlidersHorizontal className="h-5 w-5 text-indigo-600" />외부 첨삭 모델 연결</CardTitle><CardDescription>HTTPS Endpoint와 허용 도메인을 함께 검증하며, API 키는 저장 후 다시 표시되지 않습니다.</CardDescription></CardHeader><CardContent className="grid gap-4 md:grid-cols-2"><div className="space-y-2"><Label>모델 ID</Label><Input value={modelId} onChange={(event) => setModelId(event.target.value)} placeholder="예: provider-writing-v1" /></div><div className="space-y-2"><Label>Endpoint URL</Label><Input value={endpoint} onChange={(event) => setEndpoint(event.target.value)} placeholder="https://api.example.com/v1/chat/completions" /></div><div className="space-y-2"><Label>허용 도메인</Label><Input value={allowedDomains} onChange={(event) => setAllowedDomains(event.target.value)} placeholder="api.example.com, models.example.com" /><p className="text-xs text-slate-500">쉼표로 구분합니다. localhost와 사설 IP는 저장할 수 없습니다.</p></div><div className="space-y-2"><Label>요청 제한 시간(ms)</Label><Input type="number" min="1000" max="30000" value={timeoutMs} onChange={(event) => setTimeoutMs(event.target.value)} /></div><div className="space-y-2 md:col-span-2"><Label>Endpoint API 키</Label><Input type="password" value={apiKey} onChange={(event) => setApiKey(event.target.value)} placeholder="저장 시 AES-GCM으로 암호화됩니다." /></div><div className="md:col-span-2"><Button onClick={save} disabled={saveModel.isPending} className="bg-indigo-600 hover:bg-indigo-700">{saveModel.isPending ? <><Loader2 className="mr-2 h-4 w-4 animate-spin" />저장 중</> : <><ShieldCheck className="mr-2 h-4 w-4" />암호화하여 저장·활성화</>}</Button></div></CardContent></Card>
    <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle className="text-lg">등록 모델</CardTitle></CardHeader><CardContent className="space-y-3">{configs.data?.length ? configs.data.map((config: any) => <div key={config.id} className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex items-center justify-between gap-3"><div><p className="font-bold text-slate-900">{config.modelId}</p><p className="mt-1 break-all text-xs text-slate-500">{config.endpoint}</p></div><span className={config.isActive ? "rounded-full bg-emerald-100 px-2 py-1 text-xs font-bold text-emerald-700" : "rounded-full bg-slate-100 px-2 py-1 text-xs font-bold text-slate-600"}>{config.isActive ? "활성" : "비활성"}</span></div><p className="mt-3 text-xs text-slate-600">제한 시간 {config.timeoutMs}ms · 허용 도메인 {JSON.parse(config.allowedDomainsJson || "[]").join(", ")}</p></div>) : <p className="rounded-lg border border-dashed p-5 text-sm text-slate-500">등록된 외부 첨삭 모델이 없습니다. 등록 전에는 안전한 폴백 결과만 반환합니다.</p>}</CardContent></Card><Card><CardHeader><CardTitle className="text-lg">모델 운영 통계</CardTitle><CardDescription>학생 원문과 개인정보는 운영 로그에 저장하지 않습니다.</CardDescription></CardHeader><CardContent className="space-y-3">{operationStats.data?.length ? operationStats.data.map((stat: any) => <div key={stat.modelId} className="rounded-xl border border-slate-200 p-4"><div className="flex justify-between gap-3"><p className="font-bold text-slate-900">{stat.modelId}</p><p className="text-sm font-bold text-indigo-700">평균 {stat.averageLatencyMs}ms</p></div><div className="mt-3 grid grid-cols-4 gap-2 text-center text-xs"><div><p className="text-slate-500">요청</p><p className="font-bold">{stat.requestCount}</p></div><div><p className="text-slate-500">성공</p><p className="font-bold text-emerald-700">{stat.completedCount}</p></div><div><p className="text-slate-500">폴백</p><p className="font-bold text-amber-700">{stat.fallbackCount}</p></div><div><p className="text-slate-500">실패</p><p className="font-bold text-rose-700">{stat.failedCount}</p></div></div>{stat.latestError && <p className="mt-3 text-xs text-rose-700">최근 오류: {stat.latestError}</p>}</div>) : <p className="rounded-lg border border-dashed p-5 text-sm text-slate-500">아직 모델 실행 기록이 없습니다.</p>}</CardContent></Card></div>
    <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><AlertTriangle className="h-5 w-5 text-amber-600" />인간 검수 큐</CardTitle><CardDescription>저신뢰·폴백·응답 규격 오류·점수 차이 등은 자동 검수 대상으로 분류됩니다.</CardDescription></CardHeader><CardContent className="space-y-3">{reviewQueue.data?.length ? reviewQueue.data.map((item: any) => <div key={item.id} className="rounded-xl border border-amber-200 bg-amber-50/30 p-4"><p className="text-xs font-bold text-amber-800">평가 기록 #{item.evaluationRecordId}</p><p className="mt-2 text-sm text-slate-700">{(JSON.parse(item.reasonsJson || "[]") as string[]).map((reason) => REVIEW_LABELS[reason] || reason).join(" · ")}</p><div className="mt-3 flex flex-wrap items-center gap-2"><Select value={item.status} onValueChange={(status: "open" | "reviewing" | "resolved") => updateReview.mutate({ id: item.id, status })}><SelectTrigger className="h-8 w-32"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="open">대기</SelectItem><SelectItem value="reviewing">검수 중</SelectItem><SelectItem value="resolved">처리 완료</SelectItem></SelectContent></Select></div></div>) : <p className="rounded-lg border border-dashed p-5 text-sm text-slate-500">현재 검수 대기 결과가 없습니다.</p>}</CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><Clock3 className="h-5 w-5 text-indigo-600" />학습자 이의제기</CardTitle><CardDescription>접수된 이의제기 원문과 관리자 처리 이력은 삭제하지 않고 보존합니다.</CardDescription></CardHeader><CardContent className="space-y-3">{appeals.data?.length ? appeals.data.map((appeal: any) => <div key={appeal.id} className="rounded-xl border border-slate-200 p-4"><div className="flex justify-between gap-3"><p className="font-bold text-slate-900">평가 기록 #{appeal.evaluationRecordId}</p><span className="text-xs font-bold text-indigo-700">{appeal.status}</span></div><p className="mt-2 text-sm leading-6 text-slate-700">{appeal.reason}</p><Select value={appeal.status} onValueChange={(status: "submitted" | "under_review" | "accepted" | "rejected" | "resolved") => updateAppeal.mutate({ id: appeal.id, status, adminNote: appeal.adminNote || null })}><SelectTrigger className="mt-3 h-8 w-40"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="submitted">접수됨</SelectItem><SelectItem value="under_review">검토 중</SelectItem><SelectItem value="accepted">수용</SelectItem><SelectItem value="rejected">기각</SelectItem><SelectItem value="resolved">처리 완료</SelectItem></SelectContent></Select></div>) : <p className="rounded-lg border border-dashed p-5 text-sm text-slate-500">접수된 이의제기가 없습니다.</p>}</CardContent></Card></div>
    <Card className="border-slate-200"><CardHeader><CardTitle className="text-lg">인간 채점 데이터 품질 기준</CardTitle><CardDescription>QWK, Pearson 상관, 점수 임계값 recall은 인간 채점 표본이 30건 이상일 때만 공식 품질 기준으로 사용합니다.</CardDescription></CardHeader><CardContent><p className="text-sm text-slate-600">인간 채점 표본을 수집하면 운영 API에서 QWK·Pearson·recall과 표본 부족 경고를 함께 계산합니다. 현재 표본이 부족한 상태에서는 모델 품질을 공식 지표로 표시하지 않습니다.</p></CardContent></Card>
  </div></div>;
}
